# Generated by Django 2.2.13 on 2021-01-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210106_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
