# Generated by Django 2.2.13 on 2021-01-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210108_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='picture',
            new_name='picture_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
