# Generated by Django 2.2.13 on 2021-01-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_public_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.IntegerField(default=0),
        ),
    ]
