# Generated by Django 2.2.13 on 2021-01-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_customuser_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='picture_url',
            new_name='picture',
        ),
    ]
