# Generated by Django 2.2.13 on 2021-01-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210109_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.IntegerField(null=True),
        ),
    ]
