# Generated by Django 2.2.13 on 2021-01-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210109_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
