# Generated by Django 2.2.13 on 2021-01-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210109_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='timezone',
        ),
    ]
