# Generated by Django 2.2.13 on 2021-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_customuser_public_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='profile_pics'),
        ),
    ]
