# Generated by Django 2.2.13 on 2021-01-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
