# Generated by Django 2.2.13 on 2021-01-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='default.jpg', max_length=1000, upload_to='profile_pics'),
        ),
    ]
