# Generated by Django 2.2.13 on 2021-01-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20210110_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
