# Generated by Django 2.2.13 on 2021-01-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20210110_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
