# Generated by Django 2.2.13 on 2021-01-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
