# Generated by Django 2.2.13 on 2021-01-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20210111_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_token',
        ),
    ]
