# Generated by Django 2.2.13 on 2021-01-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201231_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
