# Generated by Django 2.2.13 on 2021-01-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210101_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='short_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
