# Generated by Django 2.2.13 on 2021-01-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articles_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='short_description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
