# Generated by Django 2.2.13 on 2021-01-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210104_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='text',
        ),
    ]
